### ISSUE TITLE
返回图标的锯齿很明显

### ISSUE THREAD

**Issue by tchigher** [Blankj/SwipePanel#3]
RT

**Comment by Blankj** [comment]
我放的预览图是压缩过的哈，实际效果你自己跑就知道了，即便有锯齿，你把 icon 放在高清的 drawable 就行了，揪着这么无聊的问题干嘛。

**Comment by tchigher** [comment]
是SVG的图标啊！！！

**Comment by Blankj** [comment]
这个没试过，源码是我把 drawable 转 bitmap 来显示的，可能 svg 转 bitmap 效果不好，推荐用 wbp 吧
