### ISSUE TITLE
属性设置问题

### ISSUE THREAD

**Issue by yangzbin** [Blankj/SwipePanel#5]
你好 下面这一句设置颜色无效
swipePanel.setLeftSwipeColor(R.color.colorPrimary);
如果不想要侧滑图标 不设置setLeftDrawable 则侧滑无效

**Comment by Blankj** [comment]
不设置图标是不开启的，你可以设置透明 1 像素drawable

**Comment by yangzbin** [comment]
谢谢 颜色那个问题是我获取方法有误
